package com.example.exampleapp.activities;


import com.example.exampleapp.R;
import com.example.exampleapp.listeners.LoginListener;
import com.ssmvc.ssmvc_lib.DatabaseCreator;
import com.ssmvc.ssmvc_lib.HTTPRequestManager;
import com.ssmvc.ssmvc_lib.dbDAO;

import android.os.Bundle;
import android.os.StrictMode;
import android.app.Activity;
import android.view.Menu;
import android.widget.Button;
import android.widget.EditText;

/**
 * @author mircobordoni
 * <br><br>
 * Entry point of the App.
 * This activity manages user login into the System.
 */
public class MainActivity extends Activity {
	
	private EditText username, password;
	private StrictMode.ThreadPolicy policy;
	private HTTPRequestManager httpReqMan;
	private dbDAO dao;

	/**
	 * When the activity is created it initialize the HTTPRequestManager and the Database DAO.
	 * Events generated by the Login button are managed in the LoginListener class
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.login);
		username = (EditText) findViewById(R.id.UsernameField);
		password = (EditText) findViewById(R.id.PasswordField);
		((Button)findViewById(R.id.loginButton)).setOnClickListener(new LoginListener(username, password, this));
		httpReqMan = new HTTPRequestManager(this);
		dao = new dbDAO(this);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main_activity, menu);
		return true;
	}
	
	
	public void loginButtonEnabled(boolean b){
		((Button)findViewById(R.id.loginButton)).setEnabled(b);
	}
	
	@Override
	public void onBackPressed() {
	    moveTaskToBack(true);
	}
	
	

}
