CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(60) NOT NULL,
	LAST_NAME VARCHAR(60) NOT NULL,
	BIRTH_DATE DATE,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	UNIQUE UNIQUE_USER (USERNAME),
	PRIMARY KEY (ID)
);


CREATE TABLE STATE(
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE STATE_DETAILS(
	USER_ID INT NOT NULL,
	STATE_ID INT NOT NULL,
	TIME_DATE TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID,STATE_ID,TIME_DATE),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID),
	CONSTRAINT FK_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES STATE (ID)
);

CREATE TABLE ROLE(
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE(
	USER_ID INT NOT NULL,
	ROLE_ID INT NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE,
	PRIMARY KEY (USER_ID, ROLE_ID, FROM_DATE),
	CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER (ID),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);
/*
CREATE TABLE CAN_DO(
	ROLE_ID INT NOT NULL,
	ACTIVITY_ID INT NOT NULL,
	PRIMARY KEY (ROLE_ID,ACTIVITY_ID)
	CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
	CONSTRAINT FK_ACTIVITY_ID FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY (ID),
)

CREATE TABLE ACTIVITY(
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(100) NOT NULL
	PRIMARY KEY (ID)
)*/